openapi: 3.0.3
info:
  title: Admin API
  version: 1.0.0
  contact: {}
  description: |+

    # Overview

    ### Purpose

    This specification describes service endpoints, resources and operations as well as details of requests and responses that interacts with EHR openEHR API in a RESTful manner.

    ### Status

    This specification is in the `STABLE` state, and can be downloaded as [OpenAPI specification](https://spec.openapis.org/oas/v3.0.3) file (in YAML format) [for validation](computable/OAS/ehr-validation.openapi.yaml), or [for code generators](computable/OAS/ehr-codegen.openapi.yaml).
    Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.

    The development version of this document can be found at <https://specifications.openehr.org/releases/ITS-REST/latest/ehr.html>.


servers:
  - url: https://{ehrbaseUrl}/{adminApiUrl}
    description: An example EHRbase Admin API URL.
    variables:
      baseUrl:
        default: ehrbase.org
      adminApiUrl:
        default: rest/admin
paths:
  /ehr/{ehr_id}/composition/{composition_id}:
    delete:
      tags:
        - Composition
      summary: Delete Composition
      description: >-
        Removes a composition and all related and not otherwise referenced data
        from EHRbase
      operationId: deleteComposition
      responses:
        '200':
          description: ''
    parameters:
      - name: ehr_id
        in: path
        required: true
        schema:
          type: string
      - name: composition_id
        in: path
        required: true
        schema:
          type: string
          example: '{{last_composition_id_short}}'
  /ehr/{ehr_id}:
    put:
      tags:
        - EHR
      summary: Update EHR
      description: >-
        Sends new data for a specific EHR entry which will replace the old
        content of this EHR withour history entries
      operationId: updateEhr
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              Update EHR:
                value: {}
      responses:
        '200':
          description: ''
    delete:
      tags:
        - EHR
      summary: Delete EHR
      description: >-
        Removes and EHR phyically from the database. All corresponding resources
        will also be removed including all history entries.
      operationId: deleteEhr
      responses:
        '200':
          description: ''
    parameters:
      - name: ehr_id
        in: path
        required: true
        schema:
          type: string
          example: '{{ehr_id}}'
  /ehr/{ehr_id}/contribution/{contribution_id}:
    put:
      tags:
        - Contribution
      summary: Update Contribution
      description: >-
        Replaces the content of a Contribution with the new data sent with the
        request
      operationId: updateContribution
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              Update Contribution:
                value: {}
      responses:
        '200':
          description: ''
  /ehr/{ehr_id}/directory/{directory_id}:
    delete:
      tags:
        - Directory
      summary: Delete directory
      description: Delete a diretory of an EHR physically from database
      operationId: deleteDirectory
      responses:
        '200':
          description: ''
    parameters:
      - name: ehr_id
        in: path
        required: true
        schema:
          type: string
      - name: directory_id
        in: path
        required: true
        schema:
          type: string
          example: '{{folder_id_short}}'
  /template/{template_id}:
    put:
      tags:
        - Template
      summary: Update template
      description: >-
        Updated a given template by replacing the content of the template by the
        new sent data. If there is still data referencing the template the
        request will be rejected
      operationId: updateTemplate
      requestBody:
      responses:
        '200':
          description: ''
    delete:
      tags:
        - Template
      summary: Delete template
      description: >-
        Removes a given template from database physically. If there is still
        data referencing the template the request will be rejected
      operationId: deleteTemplate
      responses:
        '200':
          description: ''
    parameters:
      - name: template_id
        in: path
        required: true
        schema:
          type: string
          example: International Patient Summary
  /template/all:
    delete:
      tags:
        - Template
      summary: Delete all templates
      description: >-
        Deletes all templates from database physically if there were no more
        Compositions referencing templates.
      operationId: deleteAllTemplates
      responses:
        '200':
          description: ''
  /query/{qualified_query_name}/{version}:
    delete:
      tags:
        - Query
      summary: Delete Stored Query Version
      description: >-
        Deletes a stored query version
      operationId: deleteStoredQuery
      responses:
        '200':
          description: ''
    parameters:
      - name: qualified_query_name
        in: path
        required: true
        schema:
          type: string
          example: org.ehrbase::compositions_with_high_blood_pressure
      - name: version
        in: path
        required: true
        schema:
          type: string
          example: 1.0.0
  /ehrbase/rest/status:
    get:
      tags:
        - Status & Management
      summary: Admin API status
      description: Get the admin base url without endpoint to test authentication
      operationId: adminApiStatus
      responses:
        '200':
          description: ''
tags:
  - name: Composition
  - name: EHR
    description: Administrative routes for EHRs
  - name: Contribution
  - name: Directory
  - name: Template
  - name: Query
  - name: Status & Management

